// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statsbudsjettportalen.Api.Data;

#nullable disable

namespace Statsbudsjettportalen.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.BudgetRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BudgetRounds");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetRoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Chapter")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FinAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FinAssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("FinListPlacement")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("GovAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ResponsibleDivision")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Post")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("PriorityNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FinAssignedTo");

                    b.HasIndex("Status");

                    b.HasIndex("BudgetRoundId", "DepartmentId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BenefitPlan")
                        .HasColumnType("text");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Chapter")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("FinAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("GovAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("TrackChangesActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FinAssessment")
                        .HasColumnType("text");

                    b.Property<string>("FinRConclusion")
                        .HasColumnType("text");

                    b.Property<string>("FinVerbal")
                        .HasColumnType("text");

                    b.Property<string>("GoalIndicator")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<string>("Post")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProposalText")
                        .HasColumnType("text");

                    b.Property<string>("SocioeconomicAnalysis")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("VerbalConclusion")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "Version")
                        .IsUnique();

                    b.ToTable("CaseContents");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseOpinion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForwardedFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpinionText")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalOpinionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestComment")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CaseId");

                    b.HasIndex("Type");

                    b.ToTable("CaseOpinions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnchorText")
                        .HasColumnType("text");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("CaseComments");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseEvents");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CaseTypeDefinitions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Clearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Clearances");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AnsweredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AskedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.ResourceLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LockedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LockedBy");

                    b.HasIndex("ResourceType", "ResourceId")
                        .IsUnique();

                    b.ToTable("ResourceLocks");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseConclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseConclusions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BudgetRoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DepartmentNamePlaceholder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ClassificationText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DepartmentListTemplates");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HeadingStyle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TemplateId", "SortOrder");

                    b.ToTable("DepartmentListTemplateSections");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetRoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("BudgetRoundId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("DepartmentLists");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentListId");

                    b.HasIndex("TemplateSectionId");

                    b.HasIndex("ParentId");

                    b.ToTable("DepartmentListSections");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListCaseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subgroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("OverrideContent")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("IncludedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("CaseId");

                    b.HasIndex("DepartmentListId", "CaseId")
                        .IsUnique();

                    b.ToTable("DepartmentListCaseEntries");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListFigure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<int>("WidthPercent")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentListId");

                    b.HasIndex("SectionId");

                    b.ToTable("DepartmentListFigures");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.RoundFieldOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetRoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinFieldKeysJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetRoundId", "CaseTypeCode")
                        .IsUnique();

                    b.ToTable("RoundFieldOverrides");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetRoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSupplement")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetRoundId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.SubmissionCase", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.HasKey("SubmissionId", "CaseId");

                    b.HasIndex("CaseId");

                    b.ToTable("SubmissionCases");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LeaderLevel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.UserDepartmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartmentAssignments");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Attachment", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Case", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.BudgetRound", "BudgetRound")
                        .WithMany("Cases")
                        .HasForeignKey("BudgetRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.Department", "Department")
                        .WithMany("Cases")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetRound");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseComment", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.CaseComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.Navigation("Case");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseContent", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("ContentVersions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseEvent", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("Events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Clearance", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("Clearances")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Question", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("Questions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Submission", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.BudgetRound", "BudgetRound")
                        .WithMany("Submissions")
                        .HasForeignKey("BudgetRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetRound");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.SubmissionCase", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.Submission", "Submission")
                        .WithMany("SubmissionCases")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.User", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.UserDepartmentAssignment", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.User", "User")
                        .WithMany("DepartmentAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseOpinion", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("Opinions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.ResourceLock", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.CaseConclusion", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany("Conclusions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListTemplateSection", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListTemplateSection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Template");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentList", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.BudgetRound", "BudgetRound")
                        .WithMany()
                        .HasForeignKey("BudgetRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("BudgetRound");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListSection", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentList", "DepartmentList")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListTemplateSection", "TemplateSection")
                        .WithMany()
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListSection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("DepartmentList");

                    b.Navigation("TemplateSection");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListCaseEntry", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentList", "DepartmentList")
                        .WithMany("CaseEntries")
                        .HasForeignKey("DepartmentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListSection", "Section")
                        .WithMany("CaseEntries")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentList");

                    b.Navigation("Section");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListFigure", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentList", "DepartmentList")
                        .WithMany("Figures")
                        .HasForeignKey("DepartmentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statsbudsjettportalen.Api.Models.DepartmentListSection", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentList");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.RoundFieldOverride", b =>
                {
                    b.HasOne("Statsbudsjettportalen.Api.Models.BudgetRound", "BudgetRound")
                        .WithMany("FieldOverrides")
                        .HasForeignKey("BudgetRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetRound");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.BudgetRound", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("FieldOverrides");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Case", b =>
                {
                    b.Navigation("Clearances");

                    b.Navigation("Conclusions");

                    b.Navigation("ContentVersions");

                    b.Navigation("Events");

                    b.Navigation("Opinions");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Department", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.Submission", b =>
                {
                    b.Navigation("SubmissionCases");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.User", b =>
                {
                    b.Navigation("DepartmentAssignments");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListTemplateSection", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentList", b =>
                {
                    b.Navigation("CaseEntries");

                    b.Navigation("Figures");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Statsbudsjettportalen.Api.Models.DepartmentListSection", b =>
                {
                    b.Navigation("CaseEntries");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
